### ISSUE TITLE
Solaris 11.3 SPARC build error

### ISSUE THREAD

**Issue by syahman** [lu-zero/libvpx#27]
hi, i cant compile on solaris 11.3 sparc, here the errors : 
 
In file included from ./vp8/common/threading.h:195:0,
                 from ./vp8/encoder/onyx_int.h:24,
                 from vp8/vp8_cx_iface.c:20:
./vpx_util/vpx_atomics.h:62:2: error: #error Unsupported architecture!
./vpx_util/vpx_atomics.h: In function ‘vpx_atomic_store_release’:
./vpx_util/vpx_atomics.h:87:3: warning: implicit declaration of function ‘vpx_atomic_memory_barrier’
gmake[1]: *** [vp8/vp8_cx_iface.c.o] Error 1
gmake: *** [.DEFAULT] Error 2

**Comment by lu-zero** [comment]
Please report it upstream, this is a personal repository for my development :)
